; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "Airplay Bridge"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "albzO"
#define MyAppURL "https://github.com/albzO/Airplay_Bridge"
#define MyAppExeName "airplay-bridge.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D7D10FFC-7F96-410D-A26F-2B1FAAE0C095}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=..\Release
OutputBaseFilename=AirPlay-Bridge-1.0.0-windows-x64-setup
SetupIconFile=..\airplay-frontend\src-tauri\icons\icon.ico
SolidCompression=yes
WizardStyle=classic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; 发布内容使用明确清单，避免把 dist 中的运行数据一起打包。
Source: "..\dist\runtime\airplay-backend.exe"; DestDir: "{app}\runtime"; Flags: ignoreversion
Source: "..\dist\runtime\*.dll"; DestDir: "{app}\runtime"; Flags: ignoreversion
Source: "..\dist\tools\homepod-test.exe"; DestDir: "{app}\tools"; Flags: ignoreversion
Source: "..\dist\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\NOTICE"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\docs\README.md"; DestDir: "{app}\docs"; Flags: ignoreversion
Source: "..\dist\docs\release-notes.md"; DestDir: "{app}\docs"; Flags: ignoreversion
Source: "..\dist\docs\licensing.md"; DestDir: "{app}\docs"; Flags: ignoreversion
Source: "..\dist\docs\error-codes.md"; DestDir: "{app}\docs"; Flags: ignoreversion
Source: "..\dist\docs\THIRD_PARTY.md"; DestDir: "{app}\docs"; Flags: ignoreversion
Source: "..\dist\licenses\airplay-cli-LICENSE"; DestDir: "{app}\licenses"; Flags: ignoreversion
Source: "..\dist\licenses\crosstools-LICENSE"; DestDir: "{app}\licenses"; Flags: ignoreversion
Source: "..\dist\licenses\openssl\LICENSE"; DestDir: "{app}\licenses\openssl"; Flags: ignoreversion
Source: "..\dist\licenses\winpthreads\COPYING"; DestDir: "{app}\licenses\winpthreads"; Flags: ignoreversion skipifsourcedoesntexist
Source: "..\dist\licenses\libwinpthread\COPYING"; DestDir: "{app}\licenses\libwinpthread"; Flags: ignoreversion skipifsourcedoesntexist
Source: "..\.local\MicrosoftEdgeWebview2Setup.exe"; Flags: dontcopy
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

[Code]
function HasWebView2At(RootKey: Integer): Boolean;
var
  Version: String;
begin
  Result := False;
  if RegQueryStringValue(
    RootKey,
    'SOFTWARE\Microsoft\EdgeUpdate\Clients\' +
    '{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}',
    'pv', Version) then
  begin
    Result := (Version <> '') and (Version <> '0.0.0.0');
  end;
end;

function HasWebView2: Boolean;
begin
  Result := HasWebView2At(HKLM32) or HasWebView2At(HKCU32);
  if IsWin64 then
    Result := Result or HasWebView2At(HKCU64);
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ExitCode: Integer;
begin
  Result := '';

  if HasWebView2 then
    Exit;

  if MsgBox(
    '需要安装 Microsoft WebView2 才能显示软件界面。' + #13#10 +
    '此步骤需要联网下载，请保持网络连接。是否继续？',
    mbConfirmation, MB_YESNO) <> IDYES then
  begin
    Result := '尚未安装 WebView2，请安装后重试。';
    Exit;
  end;

  ExtractTemporaryFile('MicrosoftEdgeWebview2Setup.exe');

  if not Exec(
    ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe'),
    '/silent /install', '', SW_HIDE,
    ewWaitUntilTerminated, ExitCode) then
  begin
    Result := '无法启动 WebView2 安装器，请重试。';
    Exit;
  end;

  Log(Format('WebView2 installer exit code: %d', [ExitCode]));

  if not HasWebView2 then
    Result :=
      'WebView2 安装未完成。请检查网络，或手动安装后重试。';
end;
